### ISSUE TITLE
multiple_chains_CA2AA resulting in aromatic ring overlap

### ISSUE THREAD

**Issue by koreyr** [ZhangGroup-MITChemistry/OpenABC#2]
Hello, 
The implementation of OpenABC is very useful, I have been able to create and simulated a condensate slab in the course grained environment provided by OpenABC-openmm. The issue I am running into happens when I try to convert my slab to the all-atom representation, such that many phenyl rings, either tyrosine or phenylalanine, from differing protein chains passing through one another, highly unphysical for proteins and problematic for running accurate condensate simulations. 

Do you have any advice to avoid or overcome this issue?

**Comment by congwang0634** [comment]
Thank you for using OpenABC. Atom clashing is a common issue when converting CG models to all-atom models, particularly in dense systems. Based on my experience, most unphysical all-atom conformations can be resolved by running energy minimization using MD software that supports double-precision calculations (I personally used the double-precision version of GROMACS). Double precision is necessary because the clashed atoms in the systems can cause forces exceed the numeric limits in single precision softwares. Then you can further relax the system by run some short MD simulations with a smaller time step (e.g. 0.5 fs or 1 fs instead of the regular 2 fs). Then, the system should stabilize. If this method doesn’t work, you can try using a different CG snapshot and repeat the process.

If multiple CG snapshots still fail, you can convert the bad all-atom configuration to a near-atomistic model (such as MARTINI), relax the system, and then convert the near-atomistic model back to the all-atom model (If you are using the MARTINI model, see https://cgmartini.nl/docs/tutorials/Martini3/Backward/). Note that you will still need a double precision software in energy minimization steps. This method can resolve all systems I have ever encountered.

**Comment by koreyr** [comment]
Thank you for your reply, the issue arises from ring-ring interlock, thus producing a result where relaxation of the system via gromacs (precision does not matter here) will not alleviate the issue. The strangest thing, that I think should be mentioned in the README.md file, is ring overlap cannot be fixed with traditional simulation, soft-core potentials as you encouraged may be a viable path forward. I opted to rotate the side-chain dihedrals to overcome the ring-ring interlocking which worked well enough, after testing many different snapshots and testing soft-core potentials. I do think this has something to do with the HB optimization, as turning it off resulted in a reduction in interlocked rings. The rings which primarily participated in interlocking were Phe-Tyr or Tyr-Tyr. Hope this detail helps with creating awareness since gromacs had zero issue running simulations of this unphysical result, what brought this to my attention was migrating my simulation to anton2 and there engine caught this issue instantly.
